"""Frozen published-session reference for the stdlib-only legacy admission gate.

XNYS dates are independently generated by exchange_calendars 4.13.2. SGE
dates are explicitly derived from the vendored upstream series, not independent
verification. Neither calendar extrapolates beyond its recorded range.
"""
from __future__ import annotations

import copy
import hashlib
import json
from datetime import date
from functools import lru_cache
from pathlib import Path

COVERAGE_POLICY_VERSION = "full-year-oos-session-calendar-v1"
DATASET = Path(__file__).with_name("session_calendar.json")
DATASET_SHA256 = "1512309b8720b6dec4be6fe051dde0d094d2b8190c02a72548c4e08d8649fcb6"
MIN_COVERAGE = .99
MAX_CONSECUTIVE_MISSING = 2


class CalendarCoverageUnavailable(ValueError):
    pass


@lru_cache(maxsize=1)
def _load():
    try:
        raw = DATASET.read_bytes()
        # Git checkout/export line endings must not change calendar identity.
        if hashlib.sha256(raw.replace(b"\r\n", b"\n")).hexdigest() != DATASET_SHA256:
            raise ValueError("reference digest mismatch")
        payload = json.loads(raw)
        if payload.get("schema_version") != 1:
            raise ValueError("reference schema mismatch")
        result = {}
        for name in ("XNYS", "SGE"):
            entry = payload["calendars"][name]
            dates = tuple(date.fromisoformat(value) for value in entry["sessions"])
            start, end = date.fromisoformat(entry["range_start"]), date.fromisoformat(entry["range_end"])
            if not dates or not start <= dates[0] <= dates[-1] <= end or any(b <= a for a, b in zip(dates, dates[1:])):
                raise ValueError("reference session order or range invalid")
            details = {key: value for key, value in entry.items() if key != "sessions"}
            details.update(calendar=name, calendar_id="calendar-" + hashlib.sha256(
                json.dumps(entry, sort_keys=True, separators=(",", ":")).encode()).hexdigest(),
                coverage_policy=COVERAGE_POLICY_VERSION)
            result[name] = (dates, start, end, details)
        return result
    except (OSError, ValueError, KeyError, TypeError, AttributeError) as exc:
        raise CalendarCoverageUnavailable("frozen session reference unavailable or invalid") from exc


def calendar_details(sleeve: str) -> dict:
    try:
        name = {"etf": "XNYS", "gold": "SGE"}[sleeve]
    except KeyError as exc:
        raise CalendarCoverageUnavailable("unknown calendar sleeve") from exc
    return copy.deepcopy(_load()[name][3])


def sessions_between(sleeve: str, start: date, end: date) -> tuple[date, ...]:
    """Known sessions only. An unsupported endpoint is unknown, never guessed."""
    details = calendar_details(sleeve)
    dates, first, last, _ = _load()[details["calendar"]]
    if start < first or end > last:
        raise CalendarCoverageUnavailable("requested dates exceed the verified calendar range")
    return tuple(value for value in dates if start <= value <= end)


def coverage(observed_dates, *, sleeve: str, start: date | None = None, end: date | None = None,
             excluded_years: tuple[int, ...] = ()) -> dict:
    """Coverage of an actual execution interval and each month/year inside it.

    A 99% annual ratio alone can hide a missing month or an outage clustered
    inside one week. Every observed month needs 99%, and no more than two
    consecutive expected sessions may be absent. Edge months are measured only
    over the requested interval, so warm-up is not confused with missing data.
    """
    observed = tuple(observed_dates)
    if not observed:
        return {"status": "fail", "issues": ["session coverage has no observed bars"]}
    start, end = start or observed[0], end or observed[-1]
    try:
        details = calendar_details(sleeve)
        expected = sessions_between(sleeve, start, end)
    except CalendarCoverageUnavailable:
        return {"status": "unknown", "coverage_policy": COVERAGE_POLICY_VERSION,
                "issues": ["session coverage calendar unavailable or outside its verified range"]}
    actual = {value for value in observed if start <= value <= end}
    all_expected = set(expected)
    # The admission layer alone authorizes named stress-year exceptions.
    # Even an explicit coverage waiver cannot excuse a noncalendar date.
    unexpected = sorted(actual - all_expected)
    waived = {str(year): {"expected": sum(value.year == year for value in expected),
                         "observed": sum(value.year == year for value in actual & all_expected)}
              for year in excluded_years}
    expected = tuple(value for value in expected if value.year not in excluded_years)
    expected_set = set(expected)
    missing = sorted(expected_set - actual)
    longest, run = 0, 0
    for session in expected:
        run = run + 1 if session not in actual else 0
        longest = max(longest, run)
    years, months, issues, year_counts, month_counts = {}, {}, [], {}, {}
    for value in expected:
        year = year_counts.setdefault(value.year, [0, 0])
        month = month_counts.setdefault((value.year, value.month), [0, 0])
        year[0] += 1
        month[0] += 1
        if value in actual:
            year[1] += 1
            month[1] += 1
    for year, (total, found) in sorted(year_counts.items()):
        years[str(year)] = {"expected": total, "observed": found, "ratio": found / total}
        if found / total < MIN_COVERAGE:
            issues.append(f"{year} session coverage {found}/{total} is below {MIN_COVERAGE:.0%}")
    for month, (total, found) in sorted(month_counts.items()):
        key = f"{month[0]}-{month[1]:02}"
        months[key] = {"expected": total, "observed": found}
        if found / total < MIN_COVERAGE:
            issues.append(f"{key} monthly session coverage {found}/{total} is below {MIN_COVERAGE:.0%}")
    if unexpected:
        issues.append(f"session coverage contains {len(unexpected)} noncalendar bars")
    if longest > MAX_CONSECUTIVE_MISSING:
        issues.append(f"session coverage has {longest} consecutive missing sessions; limit is {MAX_CONSECUTIVE_MISSING}")
    return {**details, "status": "pass" if not issues else "fail", "issues": issues,
            "from": start.isoformat(), "through": end.isoformat(),
            "excluded_years": sorted(excluded_years), "waived_year_coverage": waived,
            "expected": len(expected), "observed": len(actual.intersection(expected_set)),
            "missing_count": len(missing), "missing_sessions": [value.isoformat() for value in missing[:30]],
            "unexpected_count": len(unexpected), "unexpected_sessions": [value.isoformat() for value in unexpected[:30]],
            "longest_missing_sessions": longest, "years": years, "months": months}
