"""Generate project-scoped Codex configuration/agents/skills from shared sources."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def generated_files() -> dict[Path, str]:
    files = {}
    config = json.loads((ROOT / ".mcp.json").read_text(encoding="utf-8"))
    lines = ["# Generated by scripts/sync_runtimes.py. No credentials or machine paths.", ""]
    for name, spec in config["mcpServers"].items():
        lines.append(f"[mcp_servers.{json.dumps(name)}]")
        for key in ("command", "args", "url"):
            if key in spec:
                lines.append(f"{key} = {json.dumps(spec[key])}")
        forwarded = []
        for value in spec.get("env", {}).values():
            forwarded.extend(re.findall(r"\$\{([A-Z0-9_]+)\}", value))
        if name == "trading-copilot":
            from copilot.service import KEY_NAMES
            forwarded.extend([*KEY_NAMES, "COPILOT_DB_PATH"])
        if forwarded:
            lines.append("env_vars = " + json.dumps(sorted(set(forwarded))))
        lines += ["startup_timeout_sec = 120", "tool_timeout_sec = 180", ""]
        if name == "trading-copilot":
            tools = ["collect_market_snapshot", "get_evidence_snapshot", "get_investment_context",
                     "assess_investment_proposal", "record_investment_operation", "get_data_capabilities"]
            # Only local evidence/accounting operations authorized by the project.
            for tool in tools:
                lines += [f'[mcp_servers."trading-copilot".tools.{tool}]',
                          'approval_mode = "approve"', ""]
    files[ROOT / ".codex/config.toml"] = "\n".join(lines)
    for source in (ROOT / ".claude/agents").rglob("*.md"):
        _, meta, body = source.read_text(encoding="utf-8").split("---", 2)
        front = dict(line.split(":", 1) for line in meta.splitlines() if ":" in line)
        name = front["name"].strip()
        description = front["description"].strip().strip('"')
        files[ROOT / f".codex/agents/{name}.toml"] = (
            "# Generated from " + source.relative_to(ROOT).as_posix() + "; model inherits runtime defaults.\n" +
            "name = " + json.dumps(name) + "\n" + "description = " + json.dumps(description) + "\n" +
            "developer_instructions = " + json.dumps(body.strip(), ensure_ascii=False) + "\n")
    for source in (ROOT / ".claude/skills").rglob("*"):
        if source.is_file():
            target = ROOT / ".agents/skills" / source.relative_to(ROOT / ".claude/skills")
            files[target] = source.read_text(encoding="utf-8")
            # The distributable Codex plugin exposes the conversational entry.
            # Explicit deep orchestration remains a project skill/Claude command.
            if source.relative_to(ROOT / ".claude/skills").parts[0] == "investment-chat":
                plugin_target = ROOT / "skills" / source.relative_to(ROOT / ".claude/skills")
                files[plugin_target] = source.read_text(encoding="utf-8")
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = []
    for path, content in generated_files().items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path.relative_to(ROOT).as_posix())
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    if args.check and changed:
        print("Runtime drift: " + ", ".join(changed))
        return 1
    print(("Checked" if args.check else "Generated") + f" runtime files; {len(changed)} changed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
