"""Generate project-scoped Codex configuration and skills from shared sources."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_REFERENCE = re.compile(r"\$\{([A-Z_][A-Z0-9_]*)\}")


def _environment_references(spec: dict) -> dict[str, str]:
    result = {}
    for destination, value in spec.get("env", {}).items():
        match = ENV_REFERENCE.fullmatch(value) if isinstance(value, str) else None
        if not match:
            raise ValueError(f"MCP env mapping {destination} must reference exactly one variable")
        result[destination] = match.group(1)
    return result


def _inline_table(values: dict[str, str]) -> str:
    return "{ " + ", ".join(f"{json.dumps(key)} = {json.dumps(value)}"
                              for key, value in sorted(values.items())) + " }"


def _http_auth_lines(spec: dict) -> list[str]:
    """Use Codex's native env-backed HTTP fields; secret values never enter TOML.

    https://learn.chatgpt.com/docs/config-file/config-reference
    """
    result = []
    headers = {}
    for header, value in spec.get("headers", {}).items():
        bearer = re.fullmatch(r"Bearer \$\{([A-Z_][A-Z0-9_]*)\}", value) if isinstance(value, str) else None
        reference = ENV_REFERENCE.fullmatch(value) if isinstance(value, str) else None
        if header.lower() == "authorization" and bearer:
            result.append("bearer_token_env_var = " + json.dumps(bearer.group(1)))
        elif reference:
            headers[header] = reference.group(1)
        else:
            raise ValueError(f"MCP header {header} must use an environment reference or Bearer reference")
    if headers:
        result.append("env_http_headers = " + _inline_table(headers))
    return result


def generated_files(*, root: Path = ROOT, config: dict | None = None) -> dict[Path, str]:
    files = {}
    if config is None:
        config = json.loads((root / ".mcp.json").read_text(encoding="utf-8"))
    lines = ["# Generated by scripts/sync_runtimes.py. No credentials or machine paths.", ""]
    for name, spec in config["mcpServers"].items():
        lines.append(f"[mcp_servers.{json.dumps(name)}]")
        references = _environment_references(spec)
        renamed = any(destination != source for destination, source in references.items())
        if renamed:
            if "url" in spec or not spec.get("command"):
                raise ValueError(f"MCP server {name} has unsupported HTTP environment mappings")
            # env_vars forwards names but cannot rename them. Resolve aliases
            # in a stdlib launcher using the canonical mapping at process start.
            lines += ['command = "uv"', "args = " + json.dumps([
                "run", "--no-project", "--quiet", "--script", "scripts/mcp_env.py", name])]
        else:
            for key in ("command", "args", "url", "cwd"):
                if key in spec:
                    lines.append(f"{key} = {json.dumps(spec[key])}")
        lines += _http_auth_lines(spec)
        forwarded = list(references.values())
        if name == "trading-copilot":
            from copilot.service import KEY_NAMES
            forwarded.extend([*KEY_NAMES, "COPILOT_DB_PATH"])
        if forwarded:
            lines.append("env_vars = " + json.dumps(sorted(set(forwarded))))
        lines += ["startup_timeout_sec = 120", "tool_timeout_sec = 180", ""]
        if name == "trading-copilot":
            # Every @mcp.tool() in mcps/copilot_mcp.py must appear here. A tool
            # the server exposes and this list omits gets no approval entry in
            # the generated Codex config, so it is reachable from Claude Code
            # and not from Codex -- the two runtimes silently disagree about
            # what the plugin can do. record_retail_gold_quote was added with
            # the gold sleeve and is the reason this note exists.
            tools = ["collect_market_snapshot", "get_evidence_snapshot", "get_investment_context",
                     "assess_investment_proposal", "record_investment_operation", "get_data_capabilities",
                     "declare_holdings_coverage", "record_retail_gold_quote", "evaluate_adopted_rule"]
            # Only local evidence/accounting operations authorized by the project.
            for tool in tools:
                lines += [f'[mcp_servers."trading-copilot".tools.{tool}]',
                          'approval_mode = "approve"', ""]
    files[root / ".codex/config.toml"] = "\n".join(lines)
    for source in (root / ".claude/agents").rglob("*.md"):
        _, meta, body = source.read_text(encoding="utf-8").split("---", 2)
        front = dict(line.split(":", 1) for line in meta.splitlines() if ":" in line)
        name = front["name"].strip()
        description = front["description"].strip().strip('"')
        files[root / f".codex/agents/{name}.toml"] = (
            "# Generated from " + source.relative_to(root).as_posix() + "; model inherits runtime defaults.\n" +
            "name = " + json.dumps(name) + "\n" + "description = " + json.dumps(description) + "\n" +
            "developer_instructions = " + json.dumps(body.strip(), ensure_ascii=False) + "\n")
    for source in (root / ".claude/skills").rglob("*"):
        if source.is_file():
            target = root / ".agents/skills" / source.relative_to(root / ".claude/skills")
            files[target] = source.read_text(encoding="utf-8")
            # The distributable Codex plugin exposes the conversational entry.
            if source.relative_to(root / ".claude/skills").parts[0] == "investment-chat":
                plugin_target = root / "skills" / source.relative_to(root / ".claude/skills")
                files[plugin_target] = source.read_text(encoding="utf-8")
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = []
    for path, content in generated_files().items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path.relative_to(ROOT).as_posix())
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    if args.check and changed:
        print("Runtime drift: " + ", ".join(changed))
        return 1
    print(("Checked" if args.check else "Generated") + f" runtime files; {len(changed)} changed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
